version: '3.8'

services:
  db_media:
    image: postgres:15
    env_file:
      - ../.env
    ports:
      - "0.0.0.0:${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ../scriptsqls/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db_media_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  db_media_network:
    driver: bridge